### ISSUE TITLE
User can view list of fish

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/ajax-projet#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of fish, and watch a video about "Under the Sea: Ocean Animal Moves" from Discovery Education UK. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on the EXPLORE to see the list of fish.
Users can view details of fish by clicking on the 'LEARN MORE' button. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-13 at 10 03 56 AM](https://user-images.githubusercontent.com/91721272/173407026-0096dcd9-2edf-4671-8e59-fd5b2601fc2e.png)

![Screen Shot 2022-06-13 at 10 12 25 AM](https://user-images.githubusercontent.com/91721272/173408294-f909fa8f-4ceb-44cf-9033-7d7436973cd0.png)

![Screen Shot 2022-06-13 at 10 04 09 AM](https://user-images.githubusercontent.com/91721272/173407003-dd90030e-4fd7-4599-97d9-35bff95dc135.png)

![Screen Shot 2022-06-13 at 10 12 37 AM](https://user-images.githubusercontent.com/91721272/173408308-6f6f9a84-95fb-4819-92ec-af4cdb771653.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a `div[data-view="home"]` to the HTML.
- [x] Add a `div[data-view="list"]` to the HTML.
- [x] Listen for `click` events on the `EXPLORE` anchor and direct the user to the `list` page.
- [x] Add an empty unordered list to the `div[data-view="list"]` element in the HTML.
- [x] Add some dummy fish facts to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single fish object and returns a DOM tree that matches one of the examples in the HTML.
- [x] Use a loop to create a DOM tree for each fish in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] Ensure that each fish is given a data-fish-id attribute indicating which fish it is.
- [x] Remove the example HTML fish once the user's entries are successfully being appended to the DOM on page load.
- [x] Add navigation items to the navbar for home and search.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented-out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on mobile and desktop screen sizes for inclusion in Pull Request.
