### ISSUE TITLE
User can view details of fish

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/ajax-projet#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of fish  and press like

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the previous and next icons in the image section, the user can see other fish images. 
User can see the details of the fish.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-10 at 5 19 05 PM](https://user-images.githubusercontent.com/91721272/173164934-5e56e19e-12f7-4112-994c-61b441667e99.png)
![Screen Shot 2022-06-10 at 5 19 15 PM](https://user-images.githubusercontent.com/91721272/173164939-5796d8da-b40a-4ab0-99d8-fe34aa2715f9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a  `div[data-view="fish-detail"]` to the HTML.
- [x] Add a dummy fish fact to the table in the HTML and style them to match the wireframe.
- [x] Create a function that populates the fish details. 
- [x] Build an image carousel that includes forward and back controls and automatically cycles through a list of images.
- [x] Show the facts and pictures about the fish if the fish was clicked from the list and find the matching `data-fish-id `.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
