### ISSUE TITLE
User can search fish.

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/ajax-projet#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

A user can search for fish and get more info by clicking the `learn more` box

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on the search anchor, the user will be directed to the search page. 
The user can search for any fish they like. If the fish name does not match with the search data, it will say "Sorry, we cannot find your fish..."
If there is fish data, the user will see the fish box with a "learn more" anchor. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-12 at 5 49 17 PM](https://user-images.githubusercontent.com/91721272/173261059-870298be-24c3-4df4-b246-869f55843952.png)

![Screen Shot 2022-06-12 at 5 49 24 PM](https://user-images.githubusercontent.com/91721272/173261068-6d9f6e16-965b-43e6-b628-a4ec263c6dd2.png)

![Screen Shot 2022-06-12 at 5 47 08 PM](https://user-images.githubusercontent.com/91721272/173261074-3de00e25-f9eb-42db-b3e4-0920d2c76f28.png)
![Screen Shot 2022-06-12 at 5 47 15 PM](https://user-images.githubusercontent.com/91721272/173261083-c4525456-83ce-4f79-909a-43f7807611b8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="search"]` to the HTML.-
- [x] Find the matching fish object based on the fish name.
- [x] Show the fish when the search bar was submitted or clicked. 
- [x] If the fish was not found, show "Sorry, we cannot find your fish..."
-  **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
