### ISSUE TITLE
User can see more fish photos 

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/ajax-projet#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see more fish photos by clicking the previous and next icons.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the previous icon to return to the previous image.
User can click on the next icon to go to the next image.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-12 at 5 33 53 PM](https://user-images.githubusercontent.com/91721272/173260327-7e61f9d0-0896-4d36-a2f4-8bb16e046653.png)
![Screen Shot 2022-06-12 at 5 34 04 PM](https://user-images.githubusercontent.com/91721272/173260330-bc902423-cd27-44c0-b721-28b9a9bf6437.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set the count variable to 0. 
- [x] Define a `setImage` function that shows an image based on the number of images.
- [x] Define a `previous` function. If the user clicked on the previous icon, the number of counts goes down and shows the previous image.
- [x] Define a `next` function. if the user clicked on the next icon, the number of counts goes up and shows the next image.
- [x] Listen for `click` events on the previous icon to update the `src` attribute of the previous photo.
- [x] Listen for `click` events on the next icon to update the `src` attribute of the next photo.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
