### ISSUE TITLE
User can press like to show interest

### ISSUE THREAD

**Issue by ChorongShin** [ChorongShin/ajax-projet#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can press like to show their interest.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user presses the heart icon, it will turn into a red heart.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-13 at 12 06 25 PM](https://user-images.githubusercontent.com/91721272/173426552-54f6dcea-2e5b-49aa-b554-20b0f545a1d5.png)

![Screen Shot 2022-06-13 at 12 06 13 PM](https://user-images.githubusercontent.com/91721272/173426560-046c8d18-502f-4554-90c3-f437486b0e7d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Listen for `click` events on the heart icon.
- [x] Define a `pressedHeart` function. When the user presses the heart icon, it changes the color to red.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
